# Generated by Django 4.2.9 on 2024-01-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='claimsReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReinsurerName', models.CharField(max_length=255)),
                ('Period', models.CharField(max_length=255)),
                ('OrganisationName', models.CharField(max_length=255)),
                ('PolicyNo', models.CharField(max_length=50)),
                ('InsuredFullName', models.CharField(max_length=255)),
                ('InsuredDOB', models.DateField()),
                ('Plantype', models.CharField(max_length=50)),
                ('DOC', models.DateField()),
                ('MOP', models.CharField(max_length=50)),
                ('Term', models.IntegerField()),
                ('MaturityDate', models.DateField()),
                ('InsuredAge', models.IntegerField()),
                ('SecFullName', models.CharField(max_length=255)),
                ('SecDOB', models.DateField()),
                ('SecGender', models.CharField(max_length=10)),
                ('SecAge', models.IntegerField()),
                ('RiAge', models.IntegerField()),
                ('BasicSumAssured', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ADBSA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PTDSA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PWBSA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FESA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dc_sumFE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dc_adb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dc_ptd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dc_pwb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ret_sumFE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('st_sumFE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('st_adb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('st_ptd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('st_pwb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Rimaturity', models.DateField()),
                ('Remarks', models.TextField()),
            ],
            options={
                'db_table': '[dbo].[reinsurance]',
                'managed': False,
            },
        ),
    ]
