# Generated by Django 4.2.9 on 2024-01-16 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240116_1308'),
    ]

    operations = [
    ]
