# Generated by Django 4.2.9 on 2024-02-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumModel',
            fields=[
                ('RowId', models.AutoField(primary_key=True, serialize=False)),
                ('ProvinceCode', models.CharField(max_length=255)),
                ('BranchCode', models.CharField(max_length=50)),
                ('TodayPremium', models.DecimalField(decimal_places=2, max_digits=15)),
                ('TotalPremium', models.DecimalField(decimal_places=2, max_digits=15)),
                ('EmployeeId', models.CharField(max_length=50)),
                ('CreatedDate', models.DateField()),
                ('EditDate', models.DateField()),
            ],
        ),
    ]
