# Generated by Django 4.2.9 on 2024-01-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bankstate_delete_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonePayReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BankBalanceReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='bankstate',
            old_name='AccountNumber',
            new_name='LedgerNo',
        ),
    ]
