# Generated by Django 4.2.9 on 2024-01-29 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstate',
            name='EditDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='bankstate',
            name='LatestDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
