# Generated by Django 4.2.9 on 2024-02-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_bankstate_editdate_alter_bankstate_latestdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstate',
            name='LedgerNo',
            field=models.CharField(default='', max_length=20, null=True, unique=True),
        ),
    ]
